# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :master => {
        :box_name => "ubuntu/jammy64",
        :ip_addr => '192.168.56.150'
  },
  :logic => {
        :box_name => "ubuntu/jammy64",
        :ip_addr => '192.168.56.152'
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
      # Disable synced folder
      config.vm.synced_folder ".", "/vagrant", disabled: true

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
          end

          box.vm.provision "shell", inline: <<-SHELL
             mkdir -p ~root/.ssh
             cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
          case boxname.to_s
            when "logic"
             box.vm.provision "ansible" do |ansible|
                 ansible.limit = "all"
                 ansible.verbose = "vv"
                 ansible.playbook = "ansible/playbook.yml"
                 ansible.vault_password_file = "~/.ansible/vault.key"
                 ansible.config_file = "ansible/ansible.cfg"
             end
          end
      end
  end
end