version: '3.1'

services:

  adminer:
    image: adminer
    depends_on:
      otusdb:
        condition: service_started
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=otusdb
    ports:
      - 8080:8080

  otusdb:
    image: mysql:8.0.18
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    command: 
      --init-file /init.sql
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
      - /home/dpp/Документы/Otus/otus-subd-2024-05/hw12/users-39289-9e5604.csv:/home/root/users-39289-9e5604.csv
      - /home/dpp/Документы/Otus/otus-subd-2024-05/hw14/AdventureWorks-MySQL-with-FKs.sql:/home/root/AdventureWorks-MySQL-with-FKs.sql
    expose:
      - "3306"
    ports:
      - "3309:3306"

volumes:
  data:
