# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']
ENV["LC_ALL"] = "en_US.UTF-8"

MACHINES = {
  :master => {
        :box_name => "centos/7",
        :ip_addr => '192.168.56.150',
        # VM CPU count
        :cpus => 2,
        # VM RAM size (Mb)
        :memory => 1024
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    # Disable synced folder
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.network "private_network", ip: boxconfig[:ip_addr]
        box.vm.network :forwarded_port, guest: 5432, host: 5432

        box.vm.provider "virtualbox" do |v|
          # Set VM RAM size and CPU count
          v.memory = boxconfig[:memory]
          v.cpus = boxconfig[:cpus]
        end

        box.vm.provision "shell", inline: <<-SHELL
          timedatectl set-timezone Europe/Moscow
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL

        case boxname.to_s
          when "master"
            box.vm.provision "ansible" do |ansible|
            ansible.verbose = "vv"
            ansible.playbook = "ansible/playbook.yml"
            ansible.vault_password_file = "~/.ansible/vault.key"
            ansible.become = "true"
            ansible.limit = "all"
          end
        end
      end
  end
end
