---
# handlers file for provision/slave-setup
- name: Enable_PostgreSQL
  become: yes
  systemd:
    name: "{{ postgresql_service }}"
    enabled: yes

- name: Restart_PostgreSQL
  become: yes
  systemd:
    name: "{{ postgresql_service }}"
    state: restarted
    enabled: yes

- name: Reload_PostgreSQL
  become: yes
  systemd:
    name: "{{ postgresql_service }}"
    state: reloaded


